### ISSUE TITLE
[ADD] Create a page for the logos suggestions

### ISSUE THREAD

**Issue by ctrlaltdev** [secops-space/secops.space#16]
**Is your feature request related to a problem? Please describe.**
A page listing all the logos suggestions and their authors would be nice so we can later vote / recommend one.

**Describe the solution you'd like**
A different page that list the dirs under /logos, then the logos - then render them on the page, per nick (that should be the dir name)

**Describe alternatives you've considered**
noop

**Additional context**
Integrating a third party solution for voting might be explored later.

**Comment by jxhn** [comment]
I think one page with all the logos might be better. Just separate them with usernames as `h1`s or something.

Would just prevent an ass ton of clicking

**Comment by ctrlaltdev** [comment]
@jxhn, sorry if I wasn't explicit enough: yeah I didn't mean for the user to click to view the logo.
